dist: bionic

language: node_js
node_js:
  - node

before_install:
  - git clone https://github.com/emscripten-core/emsdk.git --depth=1
  - cd emsdk
  - ./emsdk install latest
  - ./emsdk activate latest
  - source emsdk_env.sh

script:
  - npm run package
  - npm test

notifications:
  email:
    on_success: never
    on_failure: change
