dist: bionic

language: node_js
node_js:
  - node

before_install:
  - sudo apt-get -y install emscripten

script:
  - npm run package
  - npm test

notifications:
  email:
    on_success: never
    on_failure: change
