name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        git clone 'https://github.com/emscripten-core/emsdk.git' --depth=1
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        cd ..
    - run: npm ci
    - run: npm run package
      env:
        CI: true
    - run: npm test
      env:
        CI: true
